import type { InspectorBridge } from "@vortspec/ui/useInspectorBridge";

/**
 * A stub `InspectorBridge` for component tests — the guest `<webview>` and its real
 * geometry don't exist in CT, so bridge state (placeholder, insert target, …) is
 * injected directly and command methods are no-ops (or recorders) via `overrides`.
 */
export function makeBridge(overrides: Partial<InspectorBridge> = {}): InspectorBridge {
  const noop = (): void => {};
  return {
    attach: noop,
    ready: true,
    error: null,
    tree: null,
    readout: null,
    selectedId: null,
    selectedIds: [],
    matched: {},
    matchElements: () => {},
    readouts: {},
    requestReadouts: () => {},
    marquee: null,
    selectMatching: () => {},
    subtreeTokens: {},
    subtreeElements: 0,
    requestSubtreeTokens: () => {},
    hoveredId: null,
    rects: {},
    runtimeError: null,
    clearRuntimeError: noop,
    textEdited: null,
    clearTextEdited: noop,
    contextMenu: null,
    clearContextMenu: noop,
    undoSignal: null,
    clearUndoSignal: noop,
    selectionLost: false,
    clearSelectionLost: noop,
    setText: noop,
    removeNode: noop,
    moveNode: noop,
    setClass: noop,
    select: noop,
    hover: noop,
    setMode: noop,
    commentTarget: null,
    clearCommentTarget: noop,
    insertTarget: null,
    placeholder: null,
    placeholderLost: null,
    clearPlaceholderLost: noop,
    resizePlaceholder: noop,
    dismissPlaceholder: noop,
    setPlaceholderSpec: noop,
    previewOption: noop,
    structure: null,
    requestStructure: noop,
    replayResult: null,
    clearReplayResult: noop,
    drag: null,
    dragDrop: null,
    clearDragDrop: noop,
    dragMessage: null,
    clearDragMessage: noop,
    cancelDrag: noop,
    revertMove: noop,
    clearMove: noop,
    anchorRects: {},
    watchAnchors: noop,
    scrollToAnchor: noop,
    captureThumbnail: async () => "",
    applyOverride: noop,
    clearOverride: noop,
    replayOverrides: noop,
    refreshReadout: noop,
    requestTree: noop,
    reload: noop,
    loadUrl: noop,
    serializeDom: async () => null,
    setLightMode: noop,
    // Live document (live-playground): a component test has no guest to pair with, so no page is
    // ever live here — which is exactly the not-configured path the Playground must keep working on.
    localCursor: null,
    setCursorReporting: noop,
    startLive: () => false,
    settleLive: noop,
    stopLive: noop,
    live: { adopted: false, reason: null, prepared: false },
    liveDoc: { current: null },
    ...overrides,
  };
}
