/**
 * Token → Tailwind theme bridge (change: styling-foundation-gate).
 *
 * Generated components use design-token utility classes (`bg-brand-primary`,
 * `text-default`, `text-body-regular-size`) whose names mirror the CSS variables in
 * the project's `tokens.css`. Tailwind only emits those classes if its theme maps
 * them to the variables — without the bridge every token class compiles to nothing
 * and the components render as unstyled skeletons.
 *
 * `buildTokenTheme` is the pure categorization used by the tests and is ALSO the exact
 * logic embedded in the emitted `tailwind.config.cjs` (see `renderTailwindConfigCjs`),
 * so the config self-parses `tokens.css` at load and stays in sync when tokens are
 * re-extracted. Keep the two in lockstep: the config body is this function inlined.
 */

export interface TailwindTheme {
  colors: Record<string, string>;
  fontSize: Record<string, string>;
  fontFamily: Record<string, string[]>;
  lineHeight: Record<string, string>;
  spacing: Record<string, string>;
  borderRadius: Record<string, string>;
  boxShadow: Record<string, string>;
}

/** A CSS variable name/value pair parsed from a `:root { --x: y; }` block. */
export interface CssVar {
  name: string;
  value: string;
}

/** Parse `--name: value;` declarations out of a CSS string. */
export function parseCssVars(css: string): CssVar[] {
  const out: CssVar[] = [];
  const re = /--([a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css))) out.push({ name: m[1].trim(), value: m[2].trim() });
  return out;
}

const isColor = (v: string): boolean =>
  /^(#|rgb|hsl|oklch|color\()/i.test(v) || /^var\(--/.test(v);

/**
 * Categorize the project's token variables into a Tailwind theme. Colors are exposed
 * under their raw name and with a leading `color-`/`color-text-`/`theme-` stripped, so
 * both `bg-brand-primary` (var `--color-brand-primary`) and `text-default` (var
 * `--color-text-default`) resolve. Typography `--text-*-size|-leading|-family` map to
 * fontSize/lineHeight/fontFamily; `--spacing-*`, `--radius-*`, `--shadow*` map across.
 */
export function buildTokenTheme(tokensCss: string): TailwindTheme {
  const theme: TailwindTheme = {
    colors: {},
    fontSize: {},
    fontFamily: {},
    lineHeight: {},
    spacing: {},
    borderRadius: {},
    boxShadow: {},
  };
  for (const { name, value } of parseCssVars(tokensCss)) {
    const ref = `var(--${name})`;
    if (isColor(value)) {
      theme.colors[name] = ref;
      if (name.startsWith("color-text-")) theme.colors[name.slice("color-text-".length)] = ref;
      if (name.startsWith("color-")) theme.colors[name.slice("color-".length)] = ref;
      if (name.startsWith("theme-")) theme.colors[name.slice("theme-".length)] = ref;
      continue;
    }
    if (/^text-.*-size$/.test(name)) theme.fontSize[name.slice("text-".length)] = ref;
    else if (/^text-.*-leading$/.test(name)) theme.lineHeight[name.slice("text-".length)] = ref;
    else if (/^text-.*-family$/.test(name)) theme.fontFamily[name.slice("text-".length)] = [ref];
    else if (/^font-/.test(name)) theme.fontFamily[name.slice("font-".length)] = [ref];
    else if (/^spacing-/.test(name)) theme.spacing[name.slice("spacing-".length)] = ref;
    else if (/^radius-/.test(name)) theme.borderRadius[name.slice("radius-".length)] = ref;
    else if (/^shadows?-/.test(name)) theme.boxShadow[name.replace(/^shadows?-/, "")] = ref;
  }
  return theme;
}

/**
 * The self-parsing `tailwind.config.cjs` VortSpec writes. It embeds the same
 * categorization as `buildTokenTheme`, reading `tokens.css` (at `tokenFileRel`,
 * relative to the project root) at config load so the theme reflects the current
 * tokens without a regeneration step. `contentGlobs` scan the sources that use the
 * classes; `tokenFileRel` defaults to the common `src/styles/tokens.css`.
 */
export function renderTailwindConfigCjs(tokenFileRel = "src/styles/tokens.css"): string {
  return `/**
 * Token -> Tailwind theme bridge (generated by VortSpec — styling-foundation-gate).
 *
 * The components use design-token utility classes (e.g. \`bg-brand-primary\`,
 * \`text-default\`, \`text-body-regular-size\`) whose names mirror the CSS variables in
 * ${tokenFileRel}. This config reads that file at load and maps every token into the
 * Tailwind theme, so the token classes resolve instead of compiling to nothing. It
 * re-reads on each build, so re-extracting tokens keeps the theme in sync.
 */
const fs = require("node:fs");
const path = require("node:path");

function parseVars() {
  let css = "";
  try {
    css = fs.readFileSync(path.join(__dirname, ${JSON.stringify(tokenFileRel)}), "utf8");
  } catch {
    return [];
  }
  const out = [];
  const re = /--([a-z0-9-]+)\\s*:\\s*([^;]+);/gi;
  let m;
  while ((m = re.exec(css))) out.push({ name: m[1].trim(), value: m[2].trim() });
  return out;
}

const isColor = (v) => /^(#|rgb|hsl|oklch|color\\()/i.test(v) || /^var\\(--/.test(v);

const colors = {}, fontSize = {}, fontFamily = {}, lineHeight = {}, spacing = {}, borderRadius = {}, boxShadow = {};
for (const { name, value } of parseVars()) {
  const ref = \`var(--\${name})\`;
  if (isColor(value)) {
    colors[name] = ref;
    if (name.startsWith("color-text-")) colors[name.slice("color-text-".length)] = ref;
    if (name.startsWith("color-")) colors[name.slice("color-".length)] = ref;
    if (name.startsWith("theme-")) colors[name.slice("theme-".length)] = ref;
    continue;
  }
  if (/^text-.*-size$/.test(name)) fontSize[name.slice("text-".length)] = ref;
  else if (/^text-.*-leading$/.test(name)) lineHeight[name.slice("text-".length)] = ref;
  else if (/^text-.*-family$/.test(name)) fontFamily[name.slice("text-".length)] = [ref];
  else if (/^font-/.test(name)) fontFamily[name.slice("font-".length)] = [ref];
  else if (/^spacing-/.test(name)) spacing[name.slice("spacing-".length)] = ref;
  else if (/^radius-/.test(name)) borderRadius[name.slice("radius-".length)] = ref;
  else if (/^shadows?-/.test(name)) boxShadow[name.replace(/^shadows?-/, "")] = ref;
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}", "./.storybook/**/*.{ts,tsx,mdx}"],
  theme: { extend: { colors, fontSize, fontFamily, lineHeight, spacing, borderRadius, boxShadow } },
  plugins: [],
};
`;
}
