import type { Issue } from '@/types/ir';

export const mockIssues: Issue[] = [
  // ─── Errors (5) ────────────────────────────────────────────────────────

  {
    id: 'iss_001',
    severity: 'error',
    kind: 'raw-value',
    title: 'Raw opacity on Button:disabled',
    description: 'Button uses a literal value "0.5" for disabled opacity instead of a design token. This may cause inconsistency across components with disabled states.',
    componentId: 'comp_001',
    componentName: 'Button',
    suggestedAction: 'Create token opacity/disabled = 0.5 and bind it.',
    resolved: false,
    createdAt: '2026-07-02T14:35:00Z',
  },
  {
    id: 'iss_002',
    severity: 'error',
    kind: 'raw-value',
    title: 'Raw border on Input field',
    description: 'Input Field uses a raw value "1px solid #E2E8F0" for its border instead of referencing border/default token. This value appears in 3 components.',
    componentId: 'comp_002',
    componentName: 'Input',
    suggestedAction: 'Create token border/default = 1px solid {color/neutral/200} and bind it.',
    resolved: false,
    createdAt: '2026-07-02T14:35:00Z',
  },
  {
    id: 'iss_003',
    severity: 'error',
    kind: 'raw-value',
    title: 'Raw overlay background on Modal',
    description: 'Modal overlay uses "rgba(0,0,0,0.5)" as a literal value. Overlay colors should be tokenized for consistent backdrop treatment.',
    componentId: 'comp_004',
    componentName: 'Modal',
    suggestedAction: 'Create token color/overlay = rgba(0,0,0,0.5).',
    resolved: false,
    createdAt: '2026-07-02T14:35:00Z',
  },
  {
    id: 'iss_004',
    severity: 'error',
    kind: 'raw-value',
    title: 'Raw max-width on ModalContainer',
    description: 'Modal container uses a literal "560px" for max-width. Size constraints should use sizing tokens or breakpoint tokens.',
    componentId: 'comp_004',
    componentName: 'Modal',
    suggestedAction: 'Create token sizing/modal/md = 560px.',
    resolved: false,
    createdAt: '2026-07-02T14:35:00Z',
  },
  {
    id: 'iss_005',
    severity: 'error',
    kind: 'raw-value',
    title: 'Raw border on Card footer',
    description: 'Card footer uses "1px solid #E2E8F0" as a raw border value. Same raw value appears in Input and Modal header.',
    componentId: 'comp_003',
    componentName: 'Card',
    suggestedAction: 'Bind to proposed token border/default.',
    resolved: false,
    createdAt: '2026-07-02T14:35:00Z',
  },

  // ─── Warnings (12) ──────────────────────────────────────────────────────

  {
    id: 'iss_006',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred "active" state on Button',
    description: 'The "active" state was inferred from Figma layer naming but has not been confirmed by a designer. It may be intentional or an artifact.',
    componentId: 'comp_001',
    componentName: 'Button',
    suggestedAction: 'Confirm or remove the "active" state.',
    resolved: false,
    createdAt: '2026-07-02T14:36:00Z',
  },
  {
    id: 'iss_007',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred "hover" state on Card',
    description: 'Card hover state was inferred from a layer variant named "Card/hover". The clickable prop suggests this may be valid, but it needs confirmation.',
    componentId: 'comp_003',
    componentName: 'Card',
    suggestedAction: 'Confirm hover state or mark Card as non-interactive.',
    resolved: false,
    createdAt: '2026-07-02T14:36:00Z',
  },
  {
    id: 'iss_008',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred padding axis on Card',
    description: 'Card padding variant axis (compact/default/spacious) was inferred from multiple Figma variants with differing padding values.',
    componentId: 'comp_003',
    componentName: 'Card',
    suggestedAction: 'Confirm the padding axis or collapse to a single padding value.',
    resolved: false,
    createdAt: '2026-07-02T14:36:00Z',
  },
  {
    id: 'iss_009',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred "state" axis on Input',
    description: 'Input "state" variant axis was inferred. The options (default/error/success) may overlap with the "error" boolean prop.',
    componentId: 'comp_002',
    componentName: 'Input',
    suggestedAction: 'Decide whether to use a variant axis or boolean prop for error state.',
    resolved: false,
    createdAt: '2026-07-02T14:36:00Z',
  },
  {
    id: 'iss_010',
    severity: 'warning',
    kind: 'missing-state',
    title: 'Missing focus state on Card',
    description: 'Card has a "clickable" prop but no focus state defined. Interactive elements should have a focus state for keyboard accessibility.',
    componentId: 'comp_003',
    componentName: 'Card',
    suggestedAction: 'Add a focus state with a visible focus ring.',
    resolved: false,
    createdAt: '2026-07-02T14:37:00Z',
  },
  {
    id: 'iss_011',
    severity: 'warning',
    kind: 'missing-state',
    title: 'Missing focus-visible on Button',
    description: 'Button defines a focus state but no binding for focus-visible ring was found in the structure tree.',
    componentId: 'comp_001',
    componentName: 'Button',
    suggestedAction: 'Add focus-visible ring binding using color/primary/500 at 2px offset.',
    resolved: false,
    createdAt: '2026-07-02T14:37:00Z',
  },
  {
    id: 'iss_012',
    severity: 'warning',
    kind: 'possible-duplicate',
    title: 'Possible duplicate: neutral/400 and neutral/500',
    description: 'color/neutral/400 (#94A3B8) and color/neutral/500 (#64748B) have low visual contrast (WCAG ratio 1.5:1) and similar usage patterns. Consider merging.',
    tokenId: 'tok_008',
    tokenName: 'color/neutral/400',
    suggestedAction: 'Review usage and consider merging into one token.',
    resolved: false,
    createdAt: '2026-07-02T14:38:00Z',
  },
  {
    id: 'iss_013',
    severity: 'warning',
    kind: 'possible-duplicate',
    title: 'Possible duplicate: accent/teal and info/500',
    description: 'color/accent/teal (#0D9488) and color/info/500 (#3B82F6) serve similar semantic roles in the current usage. One may be unnecessary.',
    tokenId: 'tok_017',
    tokenName: 'color/accent/teal',
    suggestedAction: 'Clarify the semantic distinction or merge.',
    resolved: false,
    createdAt: '2026-07-02T14:38:00Z',
  },
  {
    id: 'iss_014',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred spacing/8 value',
    description: 'spacing/8 (32px) was inferred from measured gaps in Figma frames. No explicit token definition was found in the source file.',
    tokenId: 'tok_038',
    tokenName: 'spacing/8',
    suggestedAction: 'Confirm the 32px value or adjust to match the spacing scale.',
    resolved: false,
    createdAt: '2026-07-02T14:38:00Z',
  },
  {
    id: 'iss_015',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred radius/xl value',
    description: 'radius/xl (16px) was inferred from rounded corners on Card and Modal. No explicit token was defined.',
    tokenId: 'tok_044',
    tokenName: 'radius/xl',
    suggestedAction: 'Confirm 16px or choose a value that fits the radius scale.',
    resolved: false,
    createdAt: '2026-07-02T14:38:00Z',
  },
  {
    id: 'iss_016',
    severity: 'warning',
    kind: 'missing-state',
    title: 'Missing ARIA attributes on Modal',
    description: 'Modal structure is missing role="dialog" and aria-modal="true". These are required for screen reader accessibility.',
    componentId: 'comp_004',
    componentName: 'Modal',
    suggestedAction: 'Add role="dialog" and aria-modal to ModalContainer node.',
    resolved: false,
    createdAt: '2026-07-02T14:39:00Z',
  },
  {
    id: 'iss_017',
    severity: 'warning',
    kind: 'unconfirmed-inference',
    title: 'Inferred overlayDismiss prop on Modal',
    description: 'The overlayDismiss boolean prop was inferred from the Figma prototype interactions. It was not explicitly defined in component properties.',
    componentId: 'comp_004',
    componentName: 'Modal',
    suggestedAction: 'Confirm overlayDismiss behavior and default value.',
    resolved: false,
    createdAt: '2026-07-02T14:39:00Z',
  },

  // ─── Info (14) ───────────────────────────────────────────────────────────

  {
    id: 'iss_018',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Token alias chain: surface/subtle -> neutral/50',
    description: 'color/surface/subtle references color/neutral/50. Consider whether the alias adds semantic value or is redundant.',
    tokenId: 'tok_015',
    tokenName: 'color/surface/subtle',
    resolved: false,
    createdAt: '2026-07-02T14:40:00Z',
  },
  {
    id: 'iss_019',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Primary/500 and info/500 are perceptually similar',
    description: 'color/primary/500 (#2563EB) and color/info/500 (#3B82F6) are both blue tones with high perceptual similarity. This is intentional in many systems but worth documenting.',
    tokenId: 'tok_001',
    tokenName: 'color/primary/500',
    resolved: false,
    createdAt: '2026-07-02T14:40:00Z',
  },
  {
    id: 'iss_020',
    severity: 'info',
    kind: 'low-contrast',
    title: 'Low contrast: neutral/400 on surface/base',
    description: 'color/neutral/400 (#94A3B8) on color/surface/base (#FFFFFF) has a contrast ratio of 3.2:1, which fails WCAG AA for normal text (4.5:1 required).',
    tokenId: 'tok_008',
    tokenName: 'color/neutral/400',
    suggestedAction: 'Use neutral/500 or darker for text on white backgrounds.',
    resolved: false,
    createdAt: '2026-07-02T14:40:00Z',
  },
  {
    id: 'iss_021',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Unused token: type/caption',
    description: 'type/caption has a pending provenance and only 7 usages. It may have been auto-extracted and could be consolidated with type/body/sm.',
    tokenId: 'tok_029',
    tokenName: 'type/caption',
    resolved: false,
    createdAt: '2026-07-02T14:41:00Z',
  },
  {
    id: 'iss_022',
    severity: 'info',
    kind: 'token-conflict',
    title: 'shadow/lg has very low usage',
    description: 'shadow/lg is used only 2 times and has "pending" provenance. Consider whether it is needed or can be removed.',
    tokenId: 'tok_048',
    tokenName: 'shadow/lg',
    resolved: false,
    createdAt: '2026-07-02T14:41:00Z',
  },
  {
    id: 'iss_023',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Spacing scale gap: no spacing/5 (20px)',
    description: 'The spacing scale jumps from spacing/4 (16px) to spacing/6 (24px). Some components may need a 20px value. Consider adding spacing/5.',
    resolved: false,
    createdAt: '2026-07-02T14:42:00Z',
  },
  {
    id: 'iss_024',
    severity: 'info',
    kind: 'low-contrast',
    title: 'Warning color on light background',
    description: 'color/warning/500 (#F59E0B) on white has a contrast ratio of 2.1:1. Warning text should use a darker variant for readability.',
    tokenId: 'tok_019',
    tokenName: 'color/warning/500',
    suggestedAction: 'Use a darker warning shade (e.g., #B45309) for text.',
    resolved: false,
    createdAt: '2026-07-02T14:42:00Z',
  },
  {
    id: 'iss_025',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Badge reuses primary/500 for multiple intents',
    description: 'Badge binds color/primary/500 for both dot background and label color across different intent variants. Intent-specific tokens may be more appropriate.',
    componentId: 'comp_005',
    componentName: 'Badge',
    resolved: false,
    createdAt: '2026-07-02T14:43:00Z',
  },
  {
    id: 'iss_026',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Raw "24px" on Modal close button',
    description: 'Modal CloseButton uses a literal "24px" for icon size. Consider using the spacing/6 (24px) token for consistency.',
    componentId: 'comp_004',
    componentName: 'Modal',
    suggestedAction: 'Bind to spacing/6 or create icon/size/md = 24px.',
    resolved: false,
    createdAt: '2026-07-02T14:43:00Z',
  },
  {
    id: 'iss_027',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Repeated border value across components',
    description: 'The raw value "1px solid #E2E8F0" appears in Input, Card, and Modal. Creating a shared border/default token would reduce duplication.',
    suggestedAction: 'Create border/default = 1px solid {color/neutral/200}.',
    resolved: false,
    createdAt: '2026-07-02T14:43:00Z',
  },
  {
    id: 'iss_028',
    severity: 'info',
    kind: 'low-contrast',
    title: 'Low contrast: accent/violet on neutral/100',
    description: 'color/accent/violet (#7C3AED) on color/neutral/100 (#F1F5F9) has a contrast ratio of 4.3:1, passing AA for large text but failing for normal text.',
    tokenId: 'tok_016',
    tokenName: 'color/accent/violet',
    resolved: false,
    createdAt: '2026-07-02T14:44:00Z',
  },
  {
    id: 'iss_029',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Input helperText prop lacks default',
    description: 'The helperText prop on Input has no default value. While optional, providing an empty string default improves code generation consistency.',
    componentId: 'comp_002',
    componentName: 'Input',
    resolved: false,
    createdAt: '2026-07-02T14:44:00Z',
  },
  {
    id: 'iss_030',
    severity: 'info',
    kind: 'token-conflict',
    title: 'Deprecated token check',
    description: 'No tokens are currently marked as deprecated. As the system evolves, track deprecated tokens to prevent them from appearing in new components.',
    resolved: false,
    createdAt: '2026-07-02T14:45:00Z',
  },
  {
    id: 'iss_031',
    severity: 'info',
    kind: 'token-conflict',
    title: 'type/code font family differs from system',
    description: 'type/code uses "JetBrains Mono" while all other typography tokens use "Inter". Ensure the code font is loaded in the target application.',
    tokenId: 'tok_030',
    tokenName: 'type/code',
    resolved: false,
    createdAt: '2026-07-02T14:45:00Z',
  },
];
