import type { Project } from '@/types/ir';

export const mockProjects: Project[] = [
  {
    id: 'proj_001',
    name: 'Meridian Design System',
    initial: 'M',
    accentColor: '#2563EB',
    tokenCount: 48,
    componentCount: 12,
    approvedCount: 3,
    completenessScore: 82,
    source: ['figma', 'zip'],
    status: 'ready',
    updatedAt: '2026-07-04T12:00:00Z',
  },
  {
    id: 'proj_002',
    name: 'Checkout Redesign',
    initial: 'C',
    accentColor: '#7C3AED',
    tokenCount: 0,
    componentCount: 0,
    approvedCount: 0,
    completenessScore: 0,
    source: ['zip'],
    status: 'importing',
    importStage: 4,
    importTotalStages: 6,
    updatedAt: '2026-07-04T11:55:00Z',
  },
  {
    id: 'proj_003',
    name: 'PatitasVIP Landing',
    initial: 'P',
    accentColor: '#F59E0B',
    tokenCount: 23,
    componentCount: 6,
    approvedCount: 0,
    completenessScore: 47,
    source: ['zip'],
    status: 'ready',
    updatedAt: '2026-07-03T09:15:00Z',
  },
];
