import { FRAMEWORK_PROFILES, idiomsFor } from "./framework-profiles";

/**
 * Per-project framework rules, emitted at setup — the fix the precedence line was standing in for.
 *
 * The toolkit ships `component-standards.md`, `styling-best-practices.md` and
 * `framework-config.md` into every project. The first two state React's architecture (CVA,
 * `cn()`, `.variants.ts`, `forwardRef`) as though it were framework-agnostic; the third
 * carries all nine frameworks' sections at once. `/generate-artifacts` loads them, so a Vue
 * project has been reading React's rules and eight other frameworks' file conventions
 * alongside its own.
 *
 * The build prompt already says its contract overrides those docs, but that only ADJUDICATES
 * a conflict that is still in context. This removes it: write the active framework's rules as
 * their own document, and prune the multi-framework doc down to the section that applies. The
 * wrong instructions are not outranked — they are never loaded.
 */

/** Where the generated per-project rules land, relative to the project root. */
export const FRAMEWORK_RULES_PATH = ".sdd-de/docs/framework-rules.md";

/**
 * The authoritative rules document for THIS project's framework, generated from the profile
 * so it cannot drift from what the build prompts say. Returns "" for an unknown framework —
 * the caller then writes nothing, and the generation prompts' STOP clause handles it.
 */
export function buildFrameworkRulesDoc(framework: string): string {
  const i = idiomsFor(framework);
  if (!i) return "";
  const key = framework.toLowerCase();
  return [
    `# Framework Rules — ${i.label}`,
    "",
    "> GENERATED by VortSpec from this project's `framework` setting. Do not edit by hand — it is",
    "> rewritten on setup and on toolkit update.",
    "",
    `This project is **${i.label}** (\`framework: ${key}\`). These rules are AUTHORITATIVE for every`,
    "component and page built here.",
    "",
    ...precedenceParagraph(key, i.label),
    "",
    "## Conventions",
    "",
    "| Aspect | Rule |",
    "|---|---|",
    `| File | ${cell(i.fileConvention)} |`,
    `| Props | ${cell(i.props)} |`,
    `| Events | ${cell(i.events)} |`,
    `| Children / slots | ${cell(i.slots)} |`,
    `| Variants | ${cell(i.variants)} |`,
    `| Style scoping | ${cell(i.styleScoping)} |`,
    `| Export | ${cell(i.exports)} |`,
    `| Refs | ${cell(i.refs)} |`,
    "",
    ...(i.pitfalls.length
      ? ["## Do not get these wrong", "", ...i.pitfalls.map((p) => `- ${p}`), ""]
      : []),
    "## Still applies",
    "",
    "**Style encapsulation.** A component owns its visual presentation. Consumers interact through",
    "props and variants, never by passing raw style overrides; a layout-only override (margin,",
    "positioning) is the exception. This principle is framework-neutral — only the MECHANISM above",
    "is framework-specific.",
    "",
    "Everything else in the shared standards that is genuinely framework-neutral still holds — atomic",
    "design levels, token discipline (no hardcoded hex/px), the accessibility baseline, and one",
    "component per variant set. Only the ARCHITECTURE above is framework-specific.",
    "",
  ].join("\n");
}

/**
 * The precedence paragraph, which differs by framework family because the underlying policy
 * does. `pruneReactArchitecture()` KEEPS the shared React architecture for react/next and
 * REMOVES it everywhere else, so a single unconditional paragraph could only be right for one
 * of them — and the version that shipped told a React project "React (Vite) is not React".
 */
function precedenceParagraph(key: string, label: string): string[] {
  if (REACT_FAMILY.has(key)) {
    return [
      "**Precedence.** The shared standards (`component-standards.md`, `styling-best-practices.md`)",
      `describe React's architecture, which IS this project's architecture — they are kept intact for`,
      `${label} and still apply. This file restates the conventions in one place and is authoritative`,
      "where the two ever disagree; it does not replace them.",
    ];
  }
  return [
    "**Precedence.** Where any other document — including `component-standards.md`,",
    "`styling-best-practices.md`, or a skill that loads them — states an architecture that",
    "conflicts with this file, THIS FILE WINS. Those documents describe React's conventions;",
    `they are not framework-agnostic, and ${label} is not React. VortSpec removes the React-only`,
    "architecture from this project's copies at setup, so they should not conflict — if you find",
    "such a rule still present, this file governs.",
  ];
}

/** Keep a rule on one Markdown table row. */
function cell(text: string): string {
  return text.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|");
}

/**
 * Which `framework-config.md` H2 headings belong to which framework. Matching is by heading
 * text because that is what the toolkit ships; the failure mode is deliberately safe — a
 * heading that matches NO pattern is treated as shared and kept, so a toolkit rename makes the
 * prune over-inclusive (harmless) rather than dropping a section the project needs.
 */
const SECTION_PATTERNS: Record<string, RegExp> = {
  react: /^#{2,3}\s*React\b/i,
  next: /^#{2,3}\s*Next\.?js\b/i,
  vue: /^#{2,3}\s*Vue\b/i,
  nuxt: /^#{2,3}\s*Nuxt\b/i,
  svelte: /^#{2,3}\s*Svelte\b/i,
  sveltekit: /^#{2,3}\s*Svelte\b/i,
  angular: /^#{2,3}\s*Angular\b/i,
  astro: /^#{2,3}\s*Astro\b/i,
  vanilla: /^#{2,3}\s*Vanilla\b/i,
};

/** Every framework-specific heading pattern, for deciding whether a section is shared. */
const ALL_SECTION_PATTERNS = [...new Set(Object.values(SECTION_PATTERNS))];

/**
 * Drop the eight framework sections that do not apply to this project, keeping the active
 * framework's section and every shared one (styling, screen-preview, token locations).
 *
 * Unknown framework returns the document unchanged: pruning to nothing would be worse than
 * leaving it, and generation is already blocked by the STOP clause in that case.
 */
export function pruneFrameworkConfigDoc(markdown: string, framework?: string | null): string {
  const keep = SECTION_PATTERNS[(framework ?? "").toLowerCase()];
  if (!keep) return markdown;

  const lines = markdown.split("\n");
  const out: string[] = [];
  let dropping = false;
  let fenced = false;
  for (const line of lines) {
    // Never read a heading inside a fenced block — snippets contain `#` comments.
    if (/^\s*```/.test(line)) fenced = !fenced;
    if (!fenced && /^#{2,3}\s/.test(line)) {
      const isFrameworkSection = ALL_SECTION_PATTERNS.some((re) => re.test(line));
      dropping = isFrameworkSection && !keep.test(line);
      if (dropping) continue;
    }
    if (!dropping) out.push(line);
  }
  // A run of separators can be left behind where sections were removed.
  return out
    .join("\n")
    .replace(/(?:^|\n)---\s*\n(\s*\n)*(?=---\s*\n)/g, "\n")
    .replace(/\n{3,}/g, "\n\n");
}


/**
 * The `##` sections in the shared standards that state REACT's component architecture as
 * though it were framework-agnostic — CVA, `cn()`, a colocated `.variants.ts`, `forwardRef`,
 * and the "never a default export" rule that `.vue`/`.svelte`/`.astro` cannot satisfy.
 *
 * These are the strongest mandates in the toolkit and they are indexed by `CLAUDE.md`, so a
 * Vue project reads them on every `/generate-artifacts`. A precedence sentence elsewhere only
 * adjudicates them; removing the section is what stops them being read.
 *
 * `##`-level only — the `###` subsections (`Required architecture`, `Component implementation
 * rules`, `Exports — one convention: NAMED exports`, the `cn()` utility, the CVA example) live
 * underneath and are carried out with their parent.
 */
const REACT_ARCHITECTURE_SECTIONS = [
  /^##\s+Style Encapsulation\b/i,
  /^##\s+Component Variant Architecture\b/i,
  /^##\s+Universal Principle\s+—\s+Style Encapsulation\b/i,
  // "All approaches use CVA for variant definitions in a colocated `.variants.ts` file",
  // with explicit rows for Vue, Svelte and Angular. The single most direct contradiction.
  /^##\s+Summary\s+—\s+Decision Table\b/i,
];

/**
 * Per-framework component-style sections. Only the active framework's is kept: Vue's scoped
 * styles are noise in an Angular project and another pattern to mistake for guidance.
 */
const FRAMEWORK_STYLE_SECTIONS: Record<string, RegExp> = {
  vue: /^##\s+Vue\b/i,
  nuxt: /^##\s+Vue\b/i,
  svelte: /^##\s+Svelte\b/i,
  sveltekit: /^##\s+Svelte\b/i,
  angular: /^##\s+Angular\b/i,
};
const ALL_FRAMEWORK_STYLE_SECTIONS = [...new Set(Object.values(FRAMEWORK_STYLE_SECTIONS))];

/**
 * Residual React mandates that survive section removal — numbered/bulleted rules inside
 * otherwise-useful sections (the Tailwind rules, a styling section's "use `cva`, `clsx`, or
 * `cn()`" bullet). Dropping the individual list item is safe where rewriting prose is not.
 */
const MANDATE_LINE = /^\s*(?:[-*]|\d+\.)\s.*(?:\bcva\b|\bCVA\b|`cn\(\)`|forwardRef|\.variants\.ts)/;

/** Frameworks whose real architecture IS the one those sections describe. */
const REACT_FAMILY = new Set(["react", "next"]);

/**
 * Strip the React-architecture sections from a shared standards doc for a non-React project,
 * leaving a pointer to the generated rules in their place.
 *
 * Returns the document unchanged for React/Next (the sections are correct there) and for an
 * unknown framework (generation is already STOPped; removing guidance would only degrade a
 * project we have decided not to build for).
 */
export function pruneReactArchitecture(markdown: string, framework?: string | null): string {
  const key = (framework ?? "").toLowerCase();
  if (!key || REACT_FAMILY.has(key) || !idiomsFor(key)) return markdown;

  const keepStyle = FRAMEWORK_STYLE_SECTIONS[key];
  const lines = markdown.split("\n");
  const out: string[] = [];
  let dropping = false;
  let fenced = false;
  let removed = false;
  for (const line of lines) {
    if (/^\s*```/.test(line)) fenced = !fenced;
    // Only a `##` ends a `##` section — `###` children belong to it.
    if (!fenced && /^##(?!#)\s/.test(line)) {
      const isOtherFrameworkStyle =
        ALL_FRAMEWORK_STYLE_SECTIONS.some((re) => re.test(line)) && !(keepStyle && keepStyle.test(line));
      dropping = REACT_ARCHITECTURE_SECTIONS.some((re) => re.test(line));
      if (isOtherFrameworkStyle) {
        dropping = true;
        removed = true;
        continue;
      }
      if (dropping) {
        removed = true;
        out.push(
          `## Component architecture — see \`framework-rules.md\``,
          "",
          "> REMOVED by VortSpec. This section prescribed React's component architecture as though it",
          "> applied to every framework. It does not, and this project is not React. The architecture",
          "> that DOES apply here is in [`framework-rules.md`](./framework-rules.md) — read that.",
          "",
        );
        continue;
      }
    }
    if (dropping) continue;
    // A retained section can still carry a React mandate as a single list item.
    if (!fenced && MANDATE_LINE.test(line)) {
      removed = true;
      continue;
    }
    out.push(line);
  }
  if (!removed) return markdown;
  return out.join("\n").replace(/\n{3,}/g, "\n\n");
}

/**
 * The line injected into the project's `CLAUDE.md` standards index so the generated rules are
 * actually LOADED. A file sitting in `.sdd-de/docs/` that nothing links is never read — the
 * doc-driven skills follow this index, not the filesystem.
 */
export const FRAMEWORK_RULES_INDEX_LINE =
  "- [Framework Rules](.sdd-de/docs/framework-rules.md) — **READ FIRST.** This project's framework " +
  "conventions, generated from its `framework` setting. Where any other standards document conflicts " +
  "with it, this one wins.";

/**
 * Insert the rules link at the TOP of `CLAUDE.md`'s standards list, so it is read before the
 * documents it overrides. Idempotent: re-running setup or a toolkit update will not duplicate it.
 * Falls back to appending a Standards section when the expected list is absent, so a toolkit
 * that reorganizes its own CLAUDE.md still ends up linking the rules.
 */
export function linkFrameworkRulesInClaudeMd(markdown: string): string {
  if (markdown.includes(".sdd-de/docs/framework-rules.md")) return markdown;
  const anchor = markdown.indexOf("- [Component Standards]");
  if (anchor !== -1) {
    return markdown.slice(0, anchor) + FRAMEWORK_RULES_INDEX_LINE + "\n" + markdown.slice(anchor);
  }
  return `${markdown.trimEnd()}\n\n## Standards\n\n${FRAMEWORK_RULES_INDEX_LINE}\n`;
}


/**
 * The unconditional `forwardRef` mandates in the shared standards, and what React actually
 * requires now.
 *
 * `pruneReactArchitecture()` deliberately KEEPS those standards for react/next because they
 * describe the right architecture — but "forwardRef is required on all components" is not
 * React 19 guidance (ref arrives as an ordinary prop) and is overbroad even on React 18 for a
 * component that exposes no ref. The generated rules say the version-aware thing, so leaving
 * the blanket mandate in place would put two instructions in context and rely on precedence to
 * pick — the exact failure this slice exists to remove.
 *
 * Phrase-level rather than line-deleting: these sit inside numbered lists whose surrounding
 * text stays correct. Fenced code samples are deliberately untouched — an example is not a
 * mandate, and rewriting code by regex is how you produce something that no longer compiles.
 */
const REACT_REF_MANDATES: [RegExp, string][] = [
  [
    /`forwardRef` is required on all components/g,
    "`ref` handling follows the React version — see `framework-rules.md` (React 19+ passes `ref` as an " +
      "ordinary prop; `forwardRef` is for React 18 and below), and only for components that expose a ref",
  ],
  [
    /\*\*`forwardRef` is required\*\* — all components must forward refs for composition/g,
    "**`ref` handling is version-dependent** — see `framework-rules.md`; forward a ref only where a " +
      "component actually exposes one",
  ],
  [/supports `forwardRef`/g, "forwards `ref` as `framework-rules.md` describes"],
];

/**
 * Remove the unconditional `forwardRef` mandate from a React/Next project's copy of the shared
 * standards, replacing it with version-aware wording. A no-op for every other framework, whose
 * copies have the whole architecture section removed by `pruneReactArchitecture()` already.
 */
export function scopeReactRefMandate(markdown: string, framework?: string | null): string {
  const key = (framework ?? "").toLowerCase();
  if (!REACT_FAMILY.has(key)) return markdown;
  let out = markdown;
  let fenced = false;
  out = out
    .split("\n")
    .map((line) => {
      if (/^\s*```/.test(line)) {
        fenced = !fenced;
        return line;
      }
      if (fenced) return line; // examples are illustrations, not instructions
      let next = line;
      for (const [re, replacement] of REACT_REF_MANDATES) next = next.replace(re, replacement);
      return next;
    })
    .join("\n");
  return out;
}


/**
 * The React `forwardRef` EXAMPLES — normative guidance, not inert illustration.
 *
 * I argued that an example is an illustration and left these alone. Thor was right that it is
 * not: `component-standards.md` labels its `forwardRef` sample `✓ GOOD`, and
 * `styling-best-practices.md` presents one as THE canonical component implementation. Both are
 * copyable, and both contradict the generated rule that React 19 passes `ref` as an ordinary
 * prop. A stale sample a reader is asked to discount is the adjudication problem in executable
 * form.
 *
 * Replaced STRUCTURALLY — by anchor and whole fenced block — rather than by regex inside code,
 * so nothing is half-rewritten into something that cannot compile. If the toolkit changes these
 * blocks the anchors stop matching, the samples stay stale, and the outcome assertions below
 * fail loudly rather than passing a no-op through.
 */

/** The default (React 19+) implementation sample, plus the older form kept clearly labelled. */
const REACT19_IMPLEMENTATION = `\`\`\`tsx
// Button.tsx — React 19+ (the default). \`ref\` is an ordinary prop; no wrapper is needed.
import * as React from 'react';
import { cn } from '@/lib/utils';
import { buttonVariants, type ButtonVariants } from './button.variants';

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    ButtonVariants {
  ref?: React.Ref<HTMLButtonElement>;
}

export const Button = ({ className, variant, size, disabled, children, ref, ...props }: ButtonProps) => (
  <button
    className={cn(buttonVariants({ variant, size }), className)}
    ref={ref}
    disabled={disabled}
    aria-disabled={disabled || undefined}
    {...props}
  >
    {children}
  </button>
);
\`\`\`

**React 18 and earlier only.** If \`package.json\` pins react below 19, and only for a component
that actually exposes a ref, wrap it instead:

\`\`\`tsx
// React 18 and earlier
const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(({ className, ...props }, ref) => (
  <button className={cn(buttonVariants(), className)} ref={ref} {...props} />
));
Button.displayName = 'Button';
export { Button };
\`\`\``;

/**
 * Version-scope the React example blocks in a React/Next project copy. No-op elsewhere — the
 * other seven lose the whole architecture section already.
 */
export function scopeReactRefExamples(markdown: string, framework?: string | null): string {
  if (!REACT_FAMILY.has((framework ?? "").toLowerCase())) return markdown;
  let out = markdown;

  // 1. The `✓ GOOD` export sample. Its POINT is named-vs-default export, so the wrapper is
  //    incidental — swapping it keeps the lesson and drops the stale normative form.
  out = out.replace(
    /^(✓ GOOD:\s+export const Button = )forwardRef\(…\)(\s*\/\/.*)$/m,
    "$1({ ref, ...props }) => …$2",
  );

  // 2. The canonical implementation block: replace the whole fenced sample that follows the
  //    heading, so the default is React 19 and the wrapper survives only under its own label.
  const anchor = out.indexOf("### Component implementation");
  if (anchor !== -1) {
    const start = out.indexOf("```tsx", anchor);
    if (start !== -1) {
      const end = out.indexOf("```", start + "```tsx".length);
      if (end !== -1) {
        out = out.slice(0, start) + REACT19_IMPLEMENTATION + out.slice(end + 3);
      }
    }
  }
  return out;
}

/** The frameworks this module can scope docs for — the ones with a profile. */
export const SCOPABLE_FRAMEWORKS = Object.keys(FRAMEWORK_PROFILES);
