import { FRAMEWORK_PROFILES, idiomsFor } from "./framework-profiles";

/**
 * Per-project framework rules, emitted at setup — the fix the precedence line was standing in for.
 *
 * The toolkit ships `component-standards.md`, `styling-best-practices.md` and
 * `framework-config.md` into every project. The first two state React's architecture (CVA,
 * `cn()`, `.variants.ts`, `forwardRef`) as though it were framework-agnostic; the third
 * carries all nine frameworks' sections at once. `/generate-artifacts` loads them, so a Vue
 * project has been reading React's rules and eight other frameworks' file conventions
 * alongside its own.
 *
 * The build prompt already says its contract overrides those docs, but that only ADJUDICATES
 * a conflict that is still in context. This removes it: write the active framework's rules as
 * their own document, and prune the multi-framework doc down to the section that applies. The
 * wrong instructions are not outranked — they are never loaded.
 */

/** Where the generated per-project rules land, relative to the project root. */
export const FRAMEWORK_RULES_PATH = ".sdd-de/docs/framework-rules.md";

/**
 * The authoritative rules document for THIS project's framework, generated from the profile
 * so it cannot drift from what the build prompts say. Returns "" for an unknown framework —
 * the caller then writes nothing, and the generation prompts' STOP clause handles it.
 */
export function buildFrameworkRulesDoc(framework: string): string {
  const i = idiomsFor(framework);
  if (!i) return "";
  const key = framework.toLowerCase();
  return [
    `# Framework Rules — ${i.label}`,
    "",
    "> GENERATED by VortSpec from this project's `framework` setting. Do not edit by hand — it is",
    "> rewritten on setup and on toolkit update.",
    "",
    `This project is **${i.label}** (\`framework: ${key}\`). These rules are AUTHORITATIVE for every`,
    "component and page built here.",
    "",
    "**Precedence.** Where any other document — including `component-standards.md`,",
    "`styling-best-practices.md`, or a skill that loads them — states an architecture that",
    "conflicts with this file, THIS FILE WINS. Those documents describe React's conventions;",
    `they are not framework-agnostic, and ${i.label} is not React.`,
    "",
    "## Conventions",
    "",
    "| Aspect | Rule |",
    "|---|---|",
    `| File | ${cell(i.fileConvention)} |`,
    `| Props | ${cell(i.props)} |`,
    `| Events | ${cell(i.events)} |`,
    `| Children / slots | ${cell(i.slots)} |`,
    `| Variants | ${cell(i.variants)} |`,
    `| Style scoping | ${cell(i.styleScoping)} |`,
    `| Export | ${cell(i.exports)} |`,
    `| Refs | ${cell(i.refs)} |`,
    "",
    ...(i.pitfalls.length
      ? ["## Do not get these wrong", "", ...i.pitfalls.map((p) => `- ${p}`), ""]
      : []),
    "## Still applies",
    "",
    "Everything in the shared standards that is genuinely framework-neutral still holds — atomic",
    "design levels, token discipline (no hardcoded hex/px), the accessibility baseline, and one",
    "component per variant set. Only the ARCHITECTURE above is framework-specific.",
    "",
  ].join("\n");
}

/** Keep a rule on one Markdown table row. */
function cell(text: string): string {
  return text.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|");
}

/**
 * Which `framework-config.md` H2 headings belong to which framework. Matching is by heading
 * text because that is what the toolkit ships; the failure mode is deliberately safe — a
 * heading that matches NO pattern is treated as shared and kept, so a toolkit rename makes the
 * prune over-inclusive (harmless) rather than dropping a section the project needs.
 */
const SECTION_PATTERNS: Record<string, RegExp> = {
  react: /^#{2,3}\s*React\b/i,
  next: /^#{2,3}\s*Next\.?js\b/i,
  vue: /^#{2,3}\s*Vue\b/i,
  nuxt: /^#{2,3}\s*Nuxt\b/i,
  svelte: /^#{2,3}\s*Svelte\b/i,
  sveltekit: /^#{2,3}\s*Svelte\b/i,
  angular: /^#{2,3}\s*Angular\b/i,
  astro: /^#{2,3}\s*Astro\b/i,
  vanilla: /^#{2,3}\s*Vanilla\b/i,
};

/** Every framework-specific heading pattern, for deciding whether a section is shared. */
const ALL_SECTION_PATTERNS = [...new Set(Object.values(SECTION_PATTERNS))];

/**
 * Drop the eight framework sections that do not apply to this project, keeping the active
 * framework's section and every shared one (styling, screen-preview, token locations).
 *
 * Unknown framework returns the document unchanged: pruning to nothing would be worse than
 * leaving it, and generation is already blocked by the STOP clause in that case.
 */
export function pruneFrameworkConfigDoc(markdown: string, framework?: string | null): string {
  const keep = SECTION_PATTERNS[(framework ?? "").toLowerCase()];
  if (!keep) return markdown;

  const lines = markdown.split("\n");
  const out: string[] = [];
  let dropping = false;
  let fenced = false;
  for (const line of lines) {
    // Never read a heading inside a fenced block — snippets contain `#` comments.
    if (/^\s*```/.test(line)) fenced = !fenced;
    if (!fenced && /^#{2,3}\s/.test(line)) {
      const isFrameworkSection = ALL_SECTION_PATTERNS.some((re) => re.test(line));
      dropping = isFrameworkSection && !keep.test(line);
      if (dropping) continue;
    }
    if (!dropping) out.push(line);
  }
  // A run of separators can be left behind where sections were removed.
  return out
    .join("\n")
    .replace(/(?:^|\n)---\s*\n(\s*\n)*(?=---\s*\n)/g, "\n")
    .replace(/\n{3,}/g, "\n\n");
}

/** The frameworks this module can scope docs for — the ones with a profile. */
export const SCOPABLE_FRAMEWORKS = Object.keys(FRAMEWORK_PROFILES);
