import { z } from "zod";
import type { EmittedFile, TokenEmitFormat } from "./token-emitters";
export type { EmittedFile } from "./token-emitters";

/**
 * The provenance ledger that makes `token_file` a DERIVED artifact instead of a file VortSpec
 * happens to overwrite — OpenSpec change: agentic-design-system, task 7.8.
 *
 * The emitters in `token-emitters.ts` answer "what should the token file contain". This module
 * answers the question that has to come first: "am I allowed to write it". A derived artifact is
 * only safe to regenerate while it is still what we last generated. The moment a human opens
 * `tailwind.config.js` and hand-tunes a theme, re-emitting would delete that work with no warning
 * and no undo — the exact failure this task exists to make impossible.
 *
 * WHY A CONTENT HASH, and not an mtime or a "generated by VortSpec" banner:
 *
 *  - **mtime lies both ways.** `git checkout`, `git clone`, a `pnpm install` that rewrites the file,
 *    or Prettier-on-save all move the mtime without changing a single token; conversely a hand edit
 *    made in the same second as the emit would look untouched. It would both cry wolf and miss the
 *    edit that matters.
 *  - **A banner is not tamper-evident.** A header comment survives an edit made underneath it, so
 *    the file would still claim to be generated after a human rewrote its body. It also cannot exist
 *    in every format (a `.ts` theme can carry a comment; a JSON-ish emit may not).
 *  - **A hash answers exactly the question asked.** "Are the bytes on disk still the bytes we
 *    wrote?" — nothing more, nothing less. It is invariant to checkout and copy, it detects a
 *    one-character change, and it needs no cooperation from the emitted format.
 *
 * The ledger lives in `.vortspec/`, alongside the canonical artifact, because it is VortSpec's
 * bookkeeping about the project — not something the project's own build consumes.
 *
 * PURE — the fs half (hashing real files, writing the ledger, applying the plan) is
 * `main/inspector/token-emit.ts`.
 */

/** Where the ledger lives, relative to the project root. Spelled once. */
export const TOKEN_EMIT_LEDGER_PATH = ".vortspec/token-emit.json";

const emitRoleSchema = z.enum(["token-file", "custom-properties"]);

export const tokenEmitLedgerEntrySchema = z.object({
  /** Project-relative POSIX path of the emitted file. */
  path: z.string(),
  role: emitRoleSchema,
  /** Hash of the exact bytes VortSpec last wrote to `path`. */
  hash: z.string(),
});

export const tokenEmitLedgerSchema = z.object({
  /** Bumped only when the ledger's own shape changes; an unknown version is treated as no ledger. */
  version: z.literal(1),
  /** The `project.yaml → styling` value the last emit ran for — recorded so a styling switch is legible in a diff. */
  styling: z.string(),
  format: z.string(),
  entries: z.array(tokenEmitLedgerEntrySchema),
});

export type TokenEmitLedgerEntry = z.infer<typeof tokenEmitLedgerEntrySchema>;
export type TokenEmitLedger = z.infer<typeof tokenEmitLedgerSchema>;

/** Parse a ledger read from disk, or null when it is absent, corrupt, or of a shape we no longer know. */
export function parseTokenEmitLedger(raw: unknown): TokenEmitLedger | null {
  const parsed = tokenEmitLedgerSchema.safeParse(raw);
  return parsed.success ? parsed.data : null;
}

/**
 * What the emit intends to do with one file.
 *
 * `diverged` is the one that is NOT an action — it is a refusal, and it is why this type exists at
 * all. Everything else can be applied without asking.
 */
export type TokenEmitDisposition =
  /** No such file yet — write it. */
  | "create"
  /** Ours, and the bytes changed — write it. */
  | "update"
  /** Ours, and the new bytes are identical — write nothing. This is the idempotence guarantee. */
  | "unchanged"
  /** Diverged, and the caller chose to keep the hand edits — write nothing, and do NOT adopt the file. */
  | "kept"
  /** Not the bytes we last wrote. Refused until the caller makes an explicit choice. */
  | "diverged";

/** One file's state going into an emit: what is on disk, what we last wrote, what we would write now. */
export interface TokenEmitCandidate {
  path: string;
  role: EmittedFile["role"];
  /** Hash of what we would write. */
  nextHash: string;
  /** Hash of what is on disk, or null when the file does not exist. */
  currentHash: string | null;
}

export interface TokenEmitPlanFile extends TokenEmitCandidate {
  disposition: TokenEmitDisposition;
  /** The hash the ledger recorded for this path, when it has one. Present on `diverged` so a caller can say what changed. */
  ledgerHash?: string;
}

export interface TokenEmitPlan {
  format: TokenEmitFormat;
  styling: string;
  files: TokenEmitPlanFile[];
  /** Paths that diverged. Non-empty ⇒ the emit must not proceed without an explicit choice. */
  diverged: string[];
  /** True when every file is `unchanged` — a re-emit with no canonical change. */
  upToDate: boolean;
}

/** How the caller resolved a divergence it was told about. */
export type DivergenceResolution =
  /** Write anyway — the user accepted losing their hand edits. */
  | "overwrite"
  /** Leave the file alone; the emit skips it and the ledger keeps pointing at the old bytes. */
  | "keep";

export interface PlanTokenEmitOptions {
  /**
   * The choice for files that diverged. Omitted ⇒ no choice has been made yet and the plan reports
   * the divergence instead of resolving it — the default has to be the safe one, because a caller
   * that forgot to ask must not silently destroy work.
   */
  onDivergence?: DivergenceResolution;
}

/**
 * Decide, per file, whether the emit may write it.
 *
 * The interesting case is "on disk but not in the ledger". It is treated as `diverged`, not as
 * `create`: a token file we have no record of writing is a file we cannot prove we own — it may be
 * the project's original hand-authored theme from before VortSpec was ever run. Assuming ownership
 * there would make the very first emit the most destructive one.
 */
export function planTokenEmit(
  input: {
    format: TokenEmitFormat;
    styling: string;
    candidates: readonly TokenEmitCandidate[];
    ledger: TokenEmitLedger | null;
  },
  options: PlanTokenEmitOptions = {},
): TokenEmitPlan {
  const recorded = new Map((input.ledger?.entries ?? []).map((entry) => [entry.path, entry.hash]));
  const files: TokenEmitPlanFile[] = input.candidates.map((candidate) => {
    const ledgerHash = recorded.get(candidate.path);
    const disposition = disposeOf(candidate, ledgerHash, options.onDivergence);
    return {
      ...candidate,
      disposition,
      ...(ledgerHash !== undefined ? { ledgerHash } : {}),
    };
  });
  return {
    format: input.format,
    styling: input.styling,
    files,
    diverged: files.filter((file) => file.disposition === "diverged").map((file) => file.path),
    upToDate: files.length > 0 && files.every((file) => file.disposition === "unchanged"),
  };
}

function disposeOf(
  candidate: TokenEmitCandidate,
  ledgerHash: string | undefined,
  resolution: DivergenceResolution | undefined,
): TokenEmitDisposition {
  if (candidate.currentHash === null) return "create";
  const ours = ledgerHash !== undefined && ledgerHash === candidate.currentHash;
  if (!ours) {
    // Hand-edited, or never ours to begin with. Only an explicit choice moves it off `diverged`.
    if (resolution === "overwrite")
      return candidate.currentHash === candidate.nextHash ? "unchanged" : "update";
    if (resolution === "keep") return "kept";
    return "diverged";
  }
  return candidate.currentHash === candidate.nextHash ? "unchanged" : "update";
}

/**
 * The message a divergence is reported with.
 *
 * Spelled here rather than at the call site so the CLI, the IPC handler and the skill all refuse in
 * the same words — and so the words always name the files and the way out.
 */
export function describeDivergence(plan: TokenEmitPlan): string {
  return (
    `Token emit stopped: ${plan.diverged.length} file(s) changed since VortSpec last wrote them — ` +
    `${plan.diverged.join(", ")}. Re-emitting would discard those edits. ` +
    `Choose: overwrite (take the emitted tokens and lose the hand edits) or keep ` +
    `(leave the file alone and emit nothing).`
  );
}

/**
 * The ledger to record after an emit.
 *
 * A `kept` file is deliberately NOT adopted. Recording the hand-edited bytes as "ours" would be the
 * quietest possible way to lose them: the very next canonical change would see the file as VortSpec's
 * own and overwrite it without a word. So a kept file carries its PREVIOUS ledger entry forward and
 * stays diverged — the user is asked again next time, which is the price of never destroying work
 * they explicitly said to keep. Same for a still-unresolved divergence.
 *
 * Entries for paths this emit did not touch are carried forward too: after a styling switch, the
 * old format's file is still on disk and still ours, and forgetting it would make switching back
 * look like a hand edit.
 */
export function nextTokenEmitLedger(
  plan: TokenEmitPlan,
  previous: TokenEmitLedger | null = null,
): TokenEmitLedger {
  const entries = new Map((previous?.entries ?? []).map((entry) => [entry.path, entry]));
  for (const file of plan.files) {
    if (file.disposition === "diverged" || file.disposition === "kept") continue;
    entries.set(file.path, {
      path: file.path,
      role: file.role,
      hash: file.disposition === "unchanged" ? (file.currentHash ?? file.nextHash) : file.nextHash,
    });
  }
  return {
    version: 1,
    styling: plan.styling,
    format: plan.format,
    // Sorted so the ledger is byte-stable across runs: emitter order must never show up as a diff.
    entries: [...entries.values()].sort((a, b) => a.path.localeCompare(b.path)),
  };
}

/** Serialize the ledger for disk — stable key order, pretty-printed, trailing newline, like the other `.vortspec/` caches. */
export function serializeTokenEmitLedger(ledger: TokenEmitLedger): string {
  const ordered = {
    version: ledger.version,
    styling: ledger.styling,
    format: ledger.format,
    entries: ledger.entries.map((entry) => ({ path: entry.path, role: entry.role, hash: entry.hash })),
  };
  return `${JSON.stringify(ordered, null, 2)}\n`;
}

// ── The summary an ingest reports back (task 7.14) ───────────────────

/**
 * What an emit that ran as part of an INGEST reports.
 *
 * A compact, serializable subset of `TokenEmitResult` (which lives in `main/` because it carries fs
 * paths and dispositions), because this rides back to the renderer inside a Figma-sync or ingest
 * result and has to cross the IPC boundary.
 *
 * `skipped` is the one status that has no equivalent in `TokenEmitResult`: emission could not run at
 * all — no `styling`, no `token_file`, no emitter for the configured approach. That is a normal
 * state for a project that has not been set up for emission yet, and it must NOT fail the ingest —
 * the tokens were still read and the artifact was still written. But it must not be silent either,
 * or the user is left wondering why their token file never appeared.
 */
export const tokenEmitSummarySchema = z.object({
  status: z.enum(["written", "up-to-date", "diverged", "read-only", "skipped"]),
  /** Project-relative paths written this run. */
  written: z.array(z.string()).default([]),
  /** Paths that changed since VortSpec last wrote them — a choice is owed before they can be. */
  diverged: z.array(z.string()).default([]),
  /** Why, ready to show a user. */
  message: z.string(),
});
export type TokenEmitSummary = z.infer<typeof tokenEmitSummarySchema>;

// ── IPC-visible result shapes (task 7.14) ────────────────────────────
//
// These live here, in zod, because the emit is now reachable over IPC and every channel's response
// is validated. The main-process modules import the inferred types rather than declaring their own,
// so there is exactly one definition of what an emit returns.

/** Compile-time guard: a zod enum that drifts from its TS union would fail validation at runtime. */
type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : never) : never;

export const tokenEmitFormatSchema = z.enum(["css", "scss", "tailwind-v3", "tailwind-v4", "ts"]);
const _formatsInStep: Exact<TokenEmitFormat, z.infer<typeof tokenEmitFormatSchema>> = true;

export const tokenEmitDispositionSchema = z.enum([
  "create",
  "update",
  "unchanged",
  "kept",
  "diverged",
]);
const _dispositionsInStep: Exact<
  TokenEmitDisposition,
  z.infer<typeof tokenEmitDispositionSchema>
> = true;

export const emittedFileRoleSchema = z.enum(["token-file", "custom-properties"]);
const _rolesInStep: Exact<EmittedFile["role"], z.infer<typeof emittedFileRoleSchema>> = true;

/** `skipped` is deliberately absent — it is an INGEST-tail outcome (`tokenEmitSummarySchema`), not
 *  something a direct emit can return: a direct emit that cannot run throws, by design. */
export const tokenEmitStatusSchema = z.enum(["written", "up-to-date", "diverged", "read-only"]);

export const tokenEmitFileReportSchema = z.object({
  /** Project-relative POSIX path. */
  path: z.string(),
  role: emittedFileRoleSchema,
  disposition: tokenEmitDispositionSchema,
});

export const tokenEmitResultSchema = z.object({
  status: tokenEmitStatusSchema,
  styling: z.string(),
  format: tokenEmitFormatSchema,
  files: z.array(tokenEmitFileReportSchema).default([]),
  written: z.array(z.string()).default([]),
  diverged: z.array(z.string()).default([]),
  kept: z.array(z.string()).default([]),
  message: z.string().optional(),
});
export type TokenEmitStatus = z.infer<typeof tokenEmitStatusSchema>;
export type TokenEmitFileReport = z.infer<typeof tokenEmitFileReportSchema>;
export type TokenEmitResult = z.infer<typeof tokenEmitResultSchema>;
