import { describe, expect, it } from "vitest";
import {
  VALIDATION_DIR,
  buildValidationPagePrompt,
  buildValidationPages,
  canGenerateValidationPage,
  importSpecifier,
  type ValidationComponent,
} from "./validation-page";

/**
 * The generated validation page — OpenSpec change: agentic-design-system, group 2b.
 *
 * The point being tested is that an audit no longer waits for a user-authored screen. Components are
 * built before screens, and that is when token discipline is cheapest to fix; waiting also makes
 * coverage accidental, since a component nobody has used yet goes silently unaudited.
 */

const COMPONENTS: ValidationComponent[] = [
  { name: "Button", file: "src/components/Button.tsx", tier: "atom", variants: ["primary", "danger"] },
  { name: "Badge", file: "src/components/Badge.tsx", tier: "atom" },
  { name: "Card", file: "src/components/Card.tsx", tier: "molecule" },
];

describe("one page per tier (task 2b.1)", () => {
  const pages = buildValidationPages(COMPONENTS, "react");

  it("emits a page per tier, not one page for everything", () => {
    // With a single page, benchmark Q4 ("used on other pages") is zero by construction — a
    // degenerate answer that looks like a measurement.
    expect(pages.map((page) => page.tier)).toEqual(["atom", "molecule"]);
    expect(pages[0].path).toBe(`${VALIDATION_DIR}/Atoms.tsx`);
  });

  it("renders every component of the tier, and one instance per variant", () => {
    const atoms = pages[0];
    expect(atoms.renders).toEqual(["Badge", "Button"]);
    expect(atoms.contents).toContain('<Button variant="primary" />');
    expect(atoms.contents).toContain('<Button variant="danger" />');
    // A component with no variants still renders once — bare.
    expect(atoms.contents).toContain("<Badge />");
  });

  it("marks each section so the audit can find it", () => {
    expect(pages[0].contents).toContain('data-validation-component="Button"');
    expect(pages[0].contents).toContain('data-validation-tier="atom"');
  });

  it("validates a component with NO recorded tier rather than dropping it", () => {
    // Dropping it would make coverage depend on classification — the accidental coverage this
    // exists to remove.
    const pages = buildValidationPages([{ name: "Loose", file: "src/components/Loose.tsx" }], "react");
    expect(pages).toHaveLength(1);
    expect(pages[0].renders).toEqual(["Loose"]);
  });

  it("says in the file that it is disposable and only the floor", () => {
    expect(pages[0].contents).toContain("GENERATED by VortSpec");
    expect(pages[0].contents).toContain("FLOOR, not the ceiling");
  });
});

describe("import specifiers resolve without an alias (task 2b.2)", () => {
  it("walks up out of the validation directory", () => {
    expect(importSpecifier("src/components/Button.tsx")).toBe("../components/Button");
    expect(importSpecifier("src/ui/atoms/Chip.tsx")).toBe("../ui/atoms/Chip");
  });

  it("never emits a bare specifier, which would read as a package", () => {
    expect(importSpecifier("components/Button.tsx").startsWith(".")).toBe(true);
  });
});

describe("fails loudly rather than writing an uncompilable page (task 2b.2)", () => {
  it("emits for the JSX family", () => {
    for (const framework of ["react", "next", "solid", "astro"])
      expect(canGenerateValidationPage(framework)).toBe(true);
  });

  it("refuses, by name, for a framework it cannot emit", () => {
    // A broken file in the user's source tree is a support ticket; a clear refusal is a decision.
    for (const framework of ["angular", "vue", "svelte", undefined]) {
      expect(canGenerateValidationPage(framework)).toBe(false);
      expect(() => buildValidationPages(COMPONENTS, framework)).toThrow(/validation-page generator/);
    }
    expect(() => buildValidationPages(COMPONENTS, "angular")).toThrow(/angular/);
  });

  it("delegates to the idioms prompt for those frameworks, asking for the SAME markers", () => {
    // One shape for the audit to read, regardless of who wrote the page.
    const prompt = buildValidationPagePrompt(COMPONENTS, "angular");
    expect(prompt).toContain("data-validation-component");
    expect(prompt).toContain("data-validation-tier");
    expect(prompt).toContain("Do NOT emit JSX into a framework that isn't JSX");
    expect(prompt).toContain("Button (src/components/Button.tsx) — variants: primary, danger");
  });
});
