import { useEffect, useMemo, useRef, useState } from "react";
import type { ManifestResult, ManifestVersion, Project } from "@vortspec/core/ipc";
import { api } from "../lib/api";
import { useAgentRun } from "../lib/useAgentRun";
import { Button, Spinner } from "@vortspec/ui/ui";
import { RunPanel } from "@vortspec/ui/RunPanel";
import { Markdown } from "@vortspec/ui/Markdown";
import { ProjectRail, projectRailItems } from "@vortspec/ui/ProjectRail";

const STAGE_ID = "design-manifest";
const GENERATE_PROMPT = [
  "Generate the AI hand-off manifest as a proper @google/design.md-format DESIGN.md. Follow these steps",
  "exactly — the filename handling matters because macOS is case-insensitive, so `design.md` and",
  "`DESIGN.md` are the SAME file and must not clobber each other.",
  "",
  "1. PRESERVE ANY DECISIONS LOG. Check the project root for an existing `DESIGN.md`/`design.md`. If its",
  "   content is NOT the @google/design.md format (i.e. it has no YAML frontmatter with design tokens —",
  "   e.g. it's a `/sync-tokens` 'Design Decisions & Token Mapping' log), MOVE it to",
  "   `.sdd-de/design-decisions.md` (create the dir; `git mv` if tracked). This frees the root name for",
  "   the Google-format file and keeps the decisions log as context.",
  "2. GENERATE. Run the /design-doc skill to write the @google/design.md-format `DESIGN.md` at the",
  "   project root, installing @google/design.md if missing. Cover EVERY built component (read the",
  "   component dir + .sdd-de/components.json). Read `.sdd-de/design-decisions.md` (if present) and fold",
  "   its deviations/decisions into the DESIGN.md 'Design Decisions' prose section. Do not overwrite the",
  "   decisions log, and do not modify the components themselves.",
  "3. KEEP THE FRONTMATTER LINT-CLEAN. In the YAML `components:` map, use ONLY @google/design.md-valid",
  "   properties (backgroundColor, textColor, typography, rounded, padding, size, height, width). Put",
  "   source paths, variant files, Storybook URLs, spec links, import snippets, and USAGE EXAMPLES in the",
  "   `## Components` prose section instead — with a Storybook URL",
  "   (http://localhost:6006/?path=/docs/<category>-<componentname>) and a usage example per component.",
  "4. VALIDATE. Run `npx @google/design.md lint DESIGN.md` and resolve every error (warnings are ok).",
  "   Confirm DESIGN.md begins with a `---` YAML frontmatter block. End with the lint summary.",
].join("\n");

type View = "rendered" | "markdown";

/**
 * Design Manifest screen (design: "Design Manifest.dc.html"). The manifest
 * (DESIGN.md) is generated by the SDD-DE `design-doc` skill through Claude Code
 * — VortSpec reads, renders (rendered/markdown), edits (gated), versions, and
 * gate-approves it. It never authors the content. File-derived; no IR store.
 */
export function DesignManifest({
  project,
  onBack,
  onOpenRun,
  onOpenPreview,
  onOpenInspector,
  onOpenHistory,
}: {
  project: Project;
  onBack: () => void;
  onOpenRun: () => void;
  onOpenPreview: () => void;
  onOpenInspector: () => void;
  onOpenHistory: () => void;
}): React.JSX.Element {
  const [manifest, setManifest] = useState<ManifestResult | null>(null);
  const [view, setView] = useState<View>("rendered");
  const [editing, setEditing] = useState(false);
  const [editDraft, setEditDraft] = useState("");
  const [saving, setSaving] = useState(false);
  const [approved, setApproved] = useState(false);
  const [versions, setVersions] = useState<ManifestVersion[] | null>(null);
  const [showVersions, setShowVersions] = useState(false);
  const [toast, setToast] = useState("");

  const gen = useAgentRun();

  function flash(msg: string): void {
    setToast(msg);
    window.setTimeout(() => setToast(""), 2400);
  }

  async function reload(): Promise<void> {
    const [m, f] = await Promise.all([
      api.getManifest(project.path),
      api.getFlow(project.path),
    ]);
    setManifest(m);
    setApproved(f?.state.stages.find((s) => s.id === STAGE_ID)?.status === "approved");
  }

  useEffect(() => {
    void reload();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [project.path]);

  async function loadVersions(): Promise<void> {
    const r = await api.listManifestVersions(project.path);
    setVersions(r.versions);
  }

  async function generate(): Promise<void> {
    // Snapshot the current manifest (if any) before regenerating over it.
    if (manifest?.exists) await api.snapshotManifest(project.path, "generate");
    await gen.start({
      prompt: GENERATE_PROMPT,
      cwd: project.path,
      allowedTools: ["Read", "Write", "Edit", "Bash"],
      bypassPermissions: true,
    });
  }

  // When generation completes, re-read the manifest and refresh versions.
  useEffect(() => {
    if (gen.model.status !== "done") return;
    void reload().then(() => flash("DESIGN.md generated"));
    void loadVersions();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gen.model.status]);

  function startEdit(): void {
    setEditDraft(manifest?.content ?? "");
    setEditing(true);
    setView("markdown");
  }
  async function saveEdit(): Promise<void> {
    setSaving(true);
    const r = await api.saveManifest(project.path, editDraft);
    setManifest(r);
    setSaving(false);
    setEditing(false);
    await loadVersions();
    flash("Saved DESIGN.md");
  }
  function cancelEdit(): void {
    setEditing(false);
  }

  async function copyMd(): Promise<void> {
    await navigator.clipboard?.writeText(manifest?.content ?? "");
    flash("DESIGN.md copied to clipboard");
  }
  function downloadMd(): void {
    const blob = new Blob([manifest?.content ?? ""], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "DESIGN.md";
    a.click();
    URL.revokeObjectURL(url);
    flash("Saved DESIGN.md");
  }

  async function approve(): Promise<void> {
    await api.snapshotManifest(project.path, "approve");
    await api.approveStage(project.path, STAGE_ID);
    setApproved(true);
    await loadVersions();
    flash("Manifest approved");
  }

  async function restoreVersion(id: string): Promise<void> {
    const r = await api.restoreManifestVersion(project.path, id);
    setManifest(r);
    await loadVersions();
    setShowVersions(false);
    flash("Version restored");
  }

  const generating = gen.running;
  const hasManifest = Boolean(manifest?.exists);
  const fileMeta = useMemo(() => {
    if (!manifest?.exists) return "";
    const lines = manifest.content.split("\n").length;
    return `${lines} lines · ${(manifest.content.length / 1024).toFixed(1)} KB`;
  }, [manifest]);

  return (
    <div className="flex h-[calc(100vh-3rem)] w-full overflow-hidden bg-vs-bg-primary text-[13px] text-vs-text-primary">
      <ProjectRail
        project={project}
        onHeaderClick={onBack}
        items={projectRailItems("manifest", {
          onFlow: onBack,
          onRun: onOpenRun,
          onPlayground: onOpenPreview,
          onTokens: onOpenInspector,
          onManifest: () => undefined,
          onHistory: onOpenHistory,
        })}
      />

      <main className="flex min-w-0 flex-1 flex-col bg-vs-bg-primary">
        {/* Header */}
        <header className="flex flex-none items-center gap-3 border-b border-vs-border-default px-8 py-4">
          <button onClick={onBack} className="text-[13px] text-vs-text-muted hover:text-vs-text-primary">
            Flow
          </button>
          <span className="text-vs-text-muted">/</span>
          <span className="text-[15px] font-semibold">Design manifest</span>
          {manifest && (
            <span className="rounded border border-vs-border-default px-1.5 py-px font-mono text-[11px] text-vs-text-secondary">
              {manifest.path}
            </span>
          )}
          {hasManifest && manifest?.format === "google" && (
            <span
              className="rounded border border-vs-success-border bg-vs-success-muted px-1.5 py-px text-[11px] text-vs-success"
              title="Valid @google/design.md format (YAML frontmatter present)"
            >
              Google format ✓
            </span>
          )}
          <div className="flex-1" />
          {hasManifest && (
            <>
              <button
                onClick={() => {
                  setShowVersions((v) => !v);
                  if (versions === null) void loadVersions();
                }}
                className="rounded-md border border-vs-border-default px-2.5 py-1 text-[11px] text-vs-text-secondary hover:border-vs-accent hover:text-vs-text-primary"
              >
                Versions{versions ? ` · ${versions.length}` : ""}
              </button>
              <div className="flex gap-0.5 rounded-lg border border-vs-border-default bg-vs-bg-surface p-0.5">
                {(["rendered", "markdown"] as View[]).map((v) => (
                  <button
                    key={v}
                    onClick={() => setView(v)}
                    className={`rounded-md px-3 py-1 text-xs capitalize transition-colors ${
                      view === v ? "bg-vs-bg-elevated text-vs-text-primary" : "text-vs-text-secondary hover:text-vs-text-primary"
                    }`}
                  >
                    {v}
                  </button>
                ))}
              </div>
            </>
          )}
        </header>

        {/* Body */}
        <div className="min-h-0 flex-1 overflow-y-auto">
          {hasManifest && !generating && !editing && manifest?.format === "decisions-log" && (
            <div className="mx-auto mt-6 flex max-w-[760px] items-start gap-3 rounded-lg border border-vs-warning-border bg-vs-warning-muted px-4 py-3">
              <span className="text-vs-warning">⚠</span>
              <div className="flex flex-1 flex-col gap-0.5 text-xs">
                <span className="font-medium text-vs-text-primary">
                  This isn't the @google/design.md format
                </span>
                <span className="text-vs-text-secondary">
                  What's here looks like a token-decisions log, not the DESIGN.md hand-off format (no YAML
                  frontmatter). Regenerate to produce the proper Google format — your decisions log is
                  preserved to <span className="font-mono">.sdd-de/design-decisions.md</span> and folded in
                  as context.
                </span>
              </div>
              <Button variant="primary" onClick={() => void generate()}>
                Regenerate
              </Button>
            </div>
          )}
          {manifest === null ? (
            <div className="flex items-center gap-2 p-8 text-sm text-vs-text-secondary">
              <Spinner /> Reading manifest…
            </div>
          ) : generating ? (
            <div className="flex min-h-[340px] items-start justify-center p-6">
              <div className="w-full max-w-2xl rounded-xl border border-vs-border-default bg-vs-bg-surface p-4">
                <div className="mb-3 flex items-center gap-2 text-sm text-vs-text-primary">
                  <Spinner /> Generating DESIGN.md with the design-doc skill (first run installs
                  @google/design.md)…
                </div>
                <RunPanel model={gen.model} onSend={(t) => void gen.send(t)} canChat={gen.canChat} />
              </div>
            </div>
          ) : !hasManifest ? (
            <EmptyState onGenerate={() => void generate()} />
          ) : editing ? (
            <EditPane
              value={editDraft}
              onChange={setEditDraft}
              onSave={() => void saveEdit()}
              onCancel={cancelEdit}
              saving={saving}
            />
          ) : view === "rendered" ? (
            <article className="mx-auto max-w-[760px] px-8 py-8">
              <Markdown text={stripFrontmatter(manifest.content)} />
            </article>
          ) : (
            <MarkdownSource
              content={manifest.content}
              path={manifest.path}
              meta={fileMeta}
              onCopy={() => void copyMd()}
              onDownload={downloadMd}
            />
          )}
        </div>

        {/* Sticky action bar */}
        {hasManifest && !generating && !editing && (
          <div className="flex-none border-t border-vs-border-default bg-vs-bg-surface px-8 py-3.5">
            {approved ? (
              <div className="flex items-center gap-3" style={{ animation: "vsFade 0.18s ease" }}>
                <span className="text-vs-success">✓</span>
                <span className="flex-1 text-[13px] text-vs-text-primary">
                  Manifest approved and written to{" "}
                  <span className="font-mono text-vs-text-secondary">{manifest?.path}</span>.
                </span>
                <Button variant="primary" onClick={onBack}>
                  Back to flow →
                </Button>
              </div>
            ) : (
              <div className="flex items-center gap-3">
                <Button variant="default" onClick={() => void generate()}>
                  Regenerate
                </Button>
                <Button variant="default" onClick={startEdit}>
                  Edit
                </Button>
                <span className="flex-1 text-[12px] text-vs-text-muted">
                  Review the manifest before publishing — this is what future AI agents read.
                </span>
                <Button variant="default" onClick={() => void copyMd()}>
                  Copy markdown
                </Button>
                <Button variant="primary" onClick={() => void approve()}>
                  Approve manifest
                </Button>
              </div>
            )}
          </div>
        )}
      </main>

      {/* Versions drawer */}
      {showVersions && (
        <VersionsDrawer
          versions={versions}
          onClose={() => setShowVersions(false)}
          onRestore={(id) => void restoreVersion(id)}
        />
      )}

      {toast && (
        <div className="fixed bottom-6 left-1/2 z-[60] flex -translate-x-1/2 items-center gap-2 rounded-lg border border-vs-border-strong bg-vs-bg-elevated px-4 py-2.5 text-xs text-vs-text-primary shadow-lg">
          <span className="text-vs-success">✓</span>
          <span className="font-mono">{toast}</span>
        </div>
      )}
    </div>
  );
}

/** Drop a leading YAML frontmatter block from the rendered view (shown raw in Markdown view). */
function stripFrontmatter(md: string): string {
  const m = md.match(/^---\n[\s\S]*?\n---\n?/);
  return m ? md.slice(m[0].length) : md;
}

function EmptyState({ onGenerate }: { onGenerate: () => void }): React.JSX.Element {
  return (
    <div className="flex min-h-[340px] items-center justify-center p-12">
      <div className="flex max-w-md flex-col items-center gap-3 rounded-xl border border-vs-border-default bg-vs-bg-surface p-8 text-center">
        <span className="text-[15px] font-semibold text-vs-text-primary">No manifest yet</span>
        <p className="text-xs leading-relaxed text-vs-text-secondary">
          Generate <span className="font-mono text-vs-text-primary">DESIGN.md</span> — the hand-off
          file any AI agent reads to build on-brand screens. VortSpec runs the SDD-DE{" "}
          <span className="font-mono">design-doc</span> skill (via{" "}
          <span className="font-mono">@google/design.md</span>) to produce and validate it.
        </p>
        <Button variant="primary" onClick={onGenerate}>
          Generate DESIGN.md
        </Button>
      </div>
    </div>
  );
}

function EditPane({
  value,
  onChange,
  onSave,
  onCancel,
  saving,
}: {
  value: string;
  onChange: (v: string) => void;
  onSave: () => void;
  onCancel: () => void;
  saving: boolean;
}): React.JSX.Element {
  return (
    <div className="mx-auto flex max-w-[900px] flex-col gap-3 px-8 py-6">
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        spellCheck={false}
        className="min-h-[420px] w-full rounded-lg border border-vs-border-default bg-vs-bg-code p-4 font-mono text-[12px] leading-relaxed text-vs-text-secondary focus:outline-none focus-visible:border-vs-accent"
      />
      <div className="flex items-center gap-3">
        <span className="flex-1 text-[11px] text-vs-text-muted">
          Saving snapshots the current version first, so you can revert.
        </span>
        <Button variant="default" onClick={onCancel}>
          Cancel
        </Button>
        <Button variant="primary" disabled={saving} onClick={onSave}>
          {saving ? "Saving…" : "Save manifest"}
        </Button>
      </div>
    </div>
  );
}

function MarkdownSource({
  content,
  path,
  meta,
  onCopy,
  onDownload,
}: {
  content: string;
  path: string;
  meta: string;
  onCopy: () => void;
  onDownload: () => void;
}): React.JSX.Element {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  const scrollRef = useRef<HTMLDivElement | null>(null);
  return (
    <div className="mx-auto max-w-[900px] px-8 py-6">
      <div className="overflow-hidden rounded-lg border border-vs-border-default">
        <div className="flex items-center gap-2.5 border-b border-vs-border-default bg-vs-bg-surface px-3.5 py-2.5">
          <span className="font-mono text-[12px] text-vs-text-primary">{path}</span>
          <span className="font-mono text-[11px] text-vs-text-muted">{meta}</span>
          <span className="flex-1" />
          <button
            onClick={onCopy}
            className="rounded-md border border-vs-border-strong px-2.5 py-1 text-[11px] text-vs-text-secondary hover:border-vs-accent hover:text-vs-text-primary"
          >
            Copy
          </button>
          <button
            onClick={onDownload}
            className="rounded-md border border-vs-border-strong px-2.5 py-1 text-[11px] text-vs-text-secondary hover:border-vs-accent hover:text-vs-text-primary"
          >
            Download
          </button>
        </div>
        <div ref={scrollRef} className="overflow-x-auto bg-vs-bg-code py-3">
          {lines.map((text, i) => (
            <div key={i} className="flex gap-3.5 px-4 hover:bg-white/[0.02]">
              <span className="w-7 flex-none select-none text-right font-mono text-[12px] leading-[1.8] text-vs-text-muted/60">
                {i + 1}
              </span>
              <span className="whitespace-pre-wrap break-words font-mono text-[12px] leading-[1.8] text-vs-text-secondary">
                {text || " "}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function VersionsDrawer({
  versions,
  onClose,
  onRestore,
}: {
  versions: ManifestVersion[] | null;
  onClose: () => void;
  onRestore: (id: string) => void;
}): React.JSX.Element {
  return (
    <aside
      className="flex w-[320px] shrink-0 flex-col border-l border-vs-border-default bg-vs-bg-surface"
      style={{ animation: "vsFade 0.18s ease" }}
    >
      <div className="flex items-center justify-between border-b border-vs-border-default px-4 pb-3 pt-4">
        <span className="text-[11px] font-semibold uppercase tracking-wide text-vs-text-muted">
          Version history
        </span>
        <button
          onClick={onClose}
          className="rounded px-1.5 py-1 leading-none text-vs-text-muted hover:bg-vs-bg-elevated hover:text-vs-text-primary"
        >
          ×
        </button>
      </div>
      <div className="flex-1 overflow-y-auto p-3">
        {versions === null ? (
          <div className="flex items-center gap-2 p-3 text-xs text-vs-text-secondary">
            <Spinner /> Loading…
          </div>
        ) : versions.length === 0 ? (
          <p className="p-3 text-xs text-vs-text-muted">
            No versions yet. Generating, editing, or approving snapshots the manifest.
          </p>
        ) : (
          <div className="flex flex-col gap-1.5">
            {versions.map((v) => (
              <div
                key={v.id}
                className="flex items-center gap-2 rounded-md border border-vs-border-default bg-vs-bg-primary px-3 py-2"
              >
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-[11px] text-vs-text-secondary">
                      {formatTs(v.timestamp)}
                    </span>
                    {v.approved && (
                      <span className="rounded-full border border-vs-border-strong px-1.5 text-[9px] text-vs-success">
                        approved
                      </span>
                    )}
                  </div>
                  <span className="font-mono text-[10px] text-vs-text-muted">
                    {(v.size / 1024).toFixed(1)} KB
                  </span>
                </div>
                <button
                  onClick={() => onRestore(v.id)}
                  className="rounded-md border border-vs-border-strong px-2 py-1 text-[10px] text-vs-text-secondary hover:border-vs-accent hover:text-vs-text-primary"
                >
                  Restore
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </aside>
  );
}

function formatTs(iso: string): string {
  // Best-effort friendly stamp without pulling a date lib.
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}
