import { join } from "node:path";
import { readFile } from "node:fs/promises";
import {
  componentMetadataSchema,
  type ComponentMetadata,
  type MetadataStatus,
  type MetadataPlan,
} from "@vortspec/core/inspector";
import { getInspectorComponents } from "./component-reader";
import { normComponentName } from "./figma-reconcile";

/**
 * AI-ready component metadata store (Plan B6). Metadata lives at
 * `.vortspec/metadata/<norm>.json` — VortSpec-owned, never in the app's source — and is
 * generated by a gated Claude Code run (`buildMetadataPrompt`), then loaded on demand to
 * ground composition/build runs with each component's intended usage + anti-patterns.
 */

const DIR = ".vortspec/metadata";

/** The metadata filename for a component (normalized so reads/writes agree). */
export function metadataFileName(name: string): string {
  return `${normComponentName(name)}.json`;
}

/** Read one component's metadata, or null when it hasn't been generated. */
export async function readComponentMetadata(projectPath: string, name: string): Promise<ComponentMetadata | null> {
  try {
    const raw = await readFile(join(projectPath, DIR, metadataFileName(name)), "utf8");
    const parsed = componentMetadataSchema.safeParse(JSON.parse(raw));
    return parsed.success ? parsed.data : null;
  } catch {
    return null;
  }
}

/** All generated metadata, keyed by normalized component name. */
export async function readAllMetadata(projectPath: string): Promise<Map<string, ComponentMetadata>> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const out = new Map<string, ComponentMetadata>();
  for (const c of comps?.components ?? []) {
    const m = await readComponentMetadata(projectPath, c.name);
    if (m) out.set(normComponentName(c.name), m);
  }
  return out;
}

/** Coverage of metadata across the roster — which components still lack it. */
export async function metadataStatus(projectPath: string): Promise<MetadataStatus> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const names = (comps?.components ?? []).map((c) => c.name);
  const missing: string[] = [];
  let withMetadata = 0;
  for (const name of names) {
    if (await readComponentMetadata(projectPath, name)) withMetadata++;
    else missing.push(name);
  }
  return { total: names.length, withMetadata, missing };
}

/**
 * Metadata coverage plus the ready-to-run generation prompt for the components still
 * missing it — what the UI needs to show a "generate" affordance and launch the run.
 */
export async function metadataPlan(projectPath: string): Promise<MetadataPlan> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const roster = comps?.components ?? [];
  const missingComps: { name: string; file: string | null }[] = [];
  for (const c of roster) {
    if (!(await readComponentMetadata(projectPath, c.name))) missingComps.push({ name: c.name, file: c.file });
  }
  return {
    total: roster.length,
    withMetadata: roster.length - missingComps.length,
    missing: missingComps.map((c) => c.name),
    prompt: missingComps.length ? buildMetadataPrompt(missingComps) : "",
  };
}

/**
 * The gated-run prompt that generates metadata for the given components. Deterministic
 * (no timestamps) so it's cache-stable. Each component gets an explicit target path so
 * the files match what `readComponentMetadata` expects.
 */
export function buildMetadataPrompt(components: { name: string; file: string | null }[]): string {
  const list = components
    .map((c) => `- ${c.name}${c.file ? ` (${c.file})` : ""} → ${DIR}/${metadataFileName(c.name)}`)
    .join("\n");
  return [
    "Generate AI-ready metadata for these design-system components so future runs use each one as intended.",
    "",
    "For EACH component: read its source (and any `.variants` sibling), then write a JSON file at the target path below with EXACTLY this shape:",
    '  { "name": "<ComponentName>", "summary": "<one line: what it is for>", "usage": ["<when/how to use>", ...], "patterns": ["<recommended composition>", ...], "antiPatterns": ["<misuse to avoid>", ...] }',
    "",
    "Rules:",
    "- Base every field on the component's REAL props, variants, and how it is used across the codebase — be concrete, not generic.",
    "- Keep each array to 2–5 tight bullets. `summary` is one sentence.",
    "- Create the `.vortspec/metadata/` directory if needed. Write ONLY these JSON files — do NOT modify any component source.",
    "",
    "Components and their target files:",
    list,
  ].join("\n");
}
