import { join } from "node:path";
import { readFile } from "node:fs/promises";
import {
  type ComponentMetadata,
  type MetadataIdentity,
  type MetadataStatus,
  type MetadataPlan,
} from "@vortspec/core/inspector";
import {
  enrichMetadataFromRoster,
  isMetadataComplete,
  metadataGaps,
  parseComponentMetadata,
} from "@vortspec/core/component-metadata";
import { getInspectorComponents } from "./component-reader";
import { normComponentName } from "./figma-reconcile";
import { safePromptField } from "./prompt-safe";

/**
 * AI-ready component metadata store (Plan B6). Metadata lives at
 * `.vortspec/metadata/<norm>.json` — VortSpec-owned, never in the app's source — and is
 * generated by a gated Claude Code run (`buildMetadataPrompt`), then loaded on demand to
 * ground composition/build runs with each component's intended usage + anti-patterns.
 */

const DIR = ".vortspec/metadata";

/** The metadata filename for a component (normalized so reads/writes agree). */
export function metadataFileName(name: string): string {
  return `${normComponentName(name)}.json`;
}

/**
 * Read one component's metadata, or null when it hasn't been generated.
 *
 * Goes through `parseComponentMetadata`, so a legacy four-field record on disk is widened HERE, in
 * memory, and every caller downstream sees the nine-section shape (task 1.2). The file itself is
 * never rewritten — see the note in `shared/component-metadata.ts` for why.
 */
export async function readComponentMetadata(projectPath: string, name: string): Promise<ComponentMetadata | null> {
  try {
    const raw = await readFile(join(projectPath, DIR, metadataFileName(name)), "utf8");
    return parseComponentMetadata(JSON.parse(raw));
  } catch {
    return null;
  }
}

/**
 * The DISCOVERY view: `identity` only, for the whole roster (task 1.3).
 *
 * The read that makes a large design system affordable to reason about. A grounded run needs to know
 * WHAT EXISTS before it can know which components matter, and paying for nine sections × the whole
 * roster to answer that would blow the token budget this change is measured against — the constraint
 * is roughly flat interactive cost. So discovery is cheap and wide; the full record is a second,
 * narrow read for the components a run actually touches (`readMetadataFor`).
 */
export async function metadataDiscovery(projectPath: string): Promise<MetadataIdentity[]> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const out: MetadataIdentity[] = [];
  for (const component of comps?.components ?? []) {
    const record = await readComponentMetadata(projectPath, component.name);
    // A component with no record still appears — its absence is the useful fact, and omitting it
    // would make the roster look smaller than it is.
    out.push(
      record?.identity ?? {
        name: component.name,
        description: "",
        ...(component.level ? { category: component.level as MetadataIdentity["category"] } : {}),
      },
    );
  }
  return out;
}

/**
 * Generated metadata for a known set of component names, keyed by normalized name.
 *
 * ENRICHED from the roster on the way out (task 1.8): the Figma reference, the atomic tier and any
 * variant axis the record does not describe are merged in from what detection already knows. Doing
 * it here — at the shared read boundary — is what makes "the docs page and grounded runs read the
 * same enriched data" true by construction rather than by two code paths agreeing to do the same
 * thing. The record always wins a conflict; enrichment only fills blanks.
 */
export async function readMetadataFor(projectPath: string, names: string[]): Promise<Map<string, ComponentMetadata>> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const roster = new Map(
    (comps?.components ?? []).map((component) => [normComponentName(component.name), component]),
  );
  const out = new Map<string, ComponentMetadata>();
  for (const name of names) {
    const record = await readComponentMetadata(projectPath, name);
    if (!record) continue;
    const key = normComponentName(name);
    out.set(key, enrichMetadataFromRoster(record, roster.get(key)));
  }
  return out;
}

/** All generated metadata, keyed by normalized component name. */
export async function readAllMetadata(projectPath: string): Promise<Map<string, ComponentMetadata>> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  return readMetadataFor(projectPath, (comps?.components ?? []).map((c) => c.name));
}

/**
 * Coverage of metadata across the roster — missing / incomplete / complete (task 1.5).
 *
 * The three-way split is the point. A migrated legacy record has a file and cannot say when to reach
 * for its component; counting it as covered reports a design system as ready while what reaches the
 * model is hollow.
 */
export async function metadataStatus(projectPath: string): Promise<MetadataStatus> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const names = (comps?.components ?? []).map((c) => c.name);
  const missing: string[] = [];
  const incomplete: { name: string; gaps: string[] }[] = [];
  let complete = 0;
  for (const name of names) {
    const record = await readComponentMetadata(projectPath, name);
    if (!record) missing.push(name);
    else if (isMetadataComplete(record)) complete++;
    else incomplete.push({ name, gaps: metadataGaps(record) });
  }
  return { total: names.length, complete, incomplete, missing, withMetadata: complete + incomplete.length };
}

/**
 * Metadata coverage plus the ready-to-run generation prompt — what the UI needs to show a "generate"
 * affordance and launch the run.
 *
 * The prompt covers the INCOMPLETE records as well as the missing ones. A migrated record is
 * precisely what needs regenerating, and leaving it out would make the affordance disappear at the
 * moment the gap it exists to close is the only one left.
 */
export async function metadataPlan(projectPath: string): Promise<MetadataPlan> {
  const comps = await getInspectorComponents(projectPath).catch(() => null);
  const roster = comps?.components ?? [];
  const status = await metadataStatus(projectPath);
  const needsWork = new Set([...status.missing, ...status.incomplete.map((entry) => entry.name)]);
  const targets = roster
    .filter((component) => needsWork.has(component.name))
    .map((component) => ({ name: component.name, file: component.file }));
  return {
    ...status,
    prompt: targets.length ? buildMetadataPrompt(targets) : "",
  };
}

/**
 * The gated-run prompt that generates metadata for the given components (task 1.4).
 *
 * Framed as a TRANSFORM OF THE SPECS, not a fresh analysis. The Component and Interaction Specs
 * already capture variants, states, props, ARIA/keyboard/WCAG, token usage, patterns and
 * anti-patterns — so asking a model to re-derive them from source is both more expensive and less
 * accurate than asking it to carry across what a person already decided. Only the three
 * analysis-derived sections (`aiHints`, `usage.commonPatterns`, `usage.antiPatterns`) are genuinely
 * new work, and those are the ones delegated to the `ai-component-metadata` skill.
 *
 * Deterministic (no timestamps) so it stays cache-stable.
 */
export function buildMetadataPrompt(components: { name: string; file: string | null }[]): string {
  // The component NAME and FILE are untrusted project data; sanitize before embedding in
  // the prompt (Plan B security). The target path is derived via metadataFileName
  // (normComponentName) so it can never escape `.vortspec/metadata/`.
  const list = components
    .map((c) => `- ${safePromptField(c.name, 80)}${c.file ? ` (${safePromptField(c.file, 120)})` : ""} → ${DIR}/${metadataFileName(c.name)}`)
    .join("\n");
  return [
    "Generate AI-ready metadata for these design-system components so future runs use each one as intended.",
    "",
    "This is mostly a TRANSFORM of what already exists, not a fresh analysis. For each component, read in this order:",
    "  1. its Component Spec and Interaction Spec under `specs/` — the authoritative source for props, variants, states, accessibility and tokens;",
    "  2. its source and any `.variants` sibling, to confirm the spec matches what was built;",
    "  3. `.vortspec/tokens.json` (the canonical token artifact) to resolve each token NAME to its value.",
    "Where the spec and the source disagree, follow the SOURCE and note it in `aiHints.context`.",
    "",
    "Write a JSON file at each target path below with this shape (omit a section you have nothing real for — never pad it):",
    JSON.stringify(
      {
        name: "<ComponentName>",
        identity: {
          name: "<ComponentName>",
          category: "atom | molecule | organism | template",
          type: "interactive | display | input | container | navigation",
          description: "<one line: what it is for>",
          importPath: "<how it is imported>",
        },
        usage: {
          useCases: ["<when to reach for it>"],
          commonPatterns: [{ name: "<pattern>", description: "<why>", code: "<runnable JSX>" }],
          antiPatterns: [{ scenario: "<what someone will try>", reason: "<why it is wrong>", alternative: "<what to do instead>" }],
        },
        variants: [{ axis: "variant", value: "primary", purpose: "<when this value is the right one>" }],
        props: [{ name: "<prop>", type: "<ts type>", default: "<default>", description: "<what it does>", required: false }],
        composition: {
          itemShape: [{ field: "<field>", type: "<ts type>", required: true, description: "<what it is>" }],
          slots: [{ name: "<slot>", description: "<what goes here>" }],
          worksWith: ["<component it is normally used with>"],
        },
        behavior: { states: [{ state: "<state>", description: "<what triggers it>" }], interactions: ["<interaction>"] },
        accessibility: { role: "<aria role>", keyboard: "<key handling>", screenReader: "<announcement>", wcag: "<criterion>", notes: [] },
        designTokens: { colors: [{ role: "background", token: "<token name>", value: "<resolved value>" }], typography: [], spacing: [], shadows: [], radius: [] },
        aiHints: { context: "<anything a generator must know>", selectionCriteria: ["<reach for this when …>"], keywords: ["<search term>"], generationRules: ["<rule>"] },
      },
      null,
      2,
    ),
    "",
    "Rules that decide whether this record is worth its tokens:",
    "- `usage.antiPatterns` MUST be triplets. A bare warning is rejected: `alternative` is the field that changes generated code, so an anti-pattern without one is not worth recording.",
    "- `aiHints.selectionCriteria` is what a composer reads FIRST — say what makes this component the right choice OVER ITS SIBLINGS, not what it does.",
    "- `variants[].purpose` is the point of the variants section. The enum values are already in the source; why to pick one is not.",
    "- `commonPatterns[].code` must be real, copy-pasteable JSX using the component's actual API.",
    "- Resolve `designTokens` values from the canonical artifact at generation time — embed the real hex/rem, not the token name alone.",
    "- Be concrete and specific to THIS component. A description that would fit any button is worse than none: it costs tokens on every run and tells the model nothing.",
    "- Create `.vortspec/metadata/` if needed. Write ONLY these JSON files — do NOT modify any component source.",
    "",
    "Components and their target files:",
    list,
  ].join("\n");
}
